# Generated by Django 3.2.4 on 2021-06-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localmingle_app', '0002_auto_20210614_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='inner_bg_img',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subtitle',
        ),
    ]
